### ISSUE TITLE
What Happened to the Orginal RDPWrap GitHub?

### ISSUE THREAD

**Issue by StarfighterJ** [SobieskiCodes/RDPWrap#3]
What Happened to the Orginal RDPWrap GitHub?

**Comment by SobieskiCodes** [comment]
https://github.com/stascorp/rdpwrap/
Don't know.
And likely won't get an answer for a long time since he hasn't been active in the project for years.
> This repository has been disabled.
Access to this repository has been disabled by GitHub Staff due to a violation of GitHub's terms of service. If you are the owner of the repository, you may reach out to GitHub Support for more information.
